services:
  chat_app:
    build: .
    depends_on:
      - db
    ports:
      - "8081:80"
    env_file:
      - .env

  db:
    image: mariadb:latest
    environment:
      MYSQL_HOST: ${MARIADB_HOST}
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOTPASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./web.sql:/docker-entrypoint-initdb.d/web.sql

volumes:
  db_data: {}
